name: Lint
on:
    push:
        branches:
            - '**'
        paths:
            - 'application/**'
jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 15.11.0
                  registry-url: https://registry.npmjs.org
            - name: Install main dependencies
              run: cd application && npm install
            - name: Runs linting
              run: cd application && npm run lint
